pipeline{

    agent none

    stages{
        stage('build'){

            agent{
                docker{
                    image 'python:2.7.16-slim'
                    args '--user root'
                }   
            }
            when{
                changeset "**/vote/**"
            }
            steps{
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('test'){
            agent{
                docker{
                    image 'python:2.7.16-slim'
                    args '--user root'
                }   
            }            
            when{
                changeset "**/vote/**"
            }
            steps{
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                    sh 'nosetests -v'
                }
            }
        }
        stage('docker-package'){
            agent any
            when{
                changeset "**/vote/**"
            }
            steps{
                script{
                    docker.withRegistry('https://index.docker.io/v1/','dockerlogin'){
                        def voteImage = docker.build("test12481248xenon/vote:v${env.BUILD_ID}","./vote")
                        voteImage.push()
                        voteImage.push("${env.BRANCH_NAME}")
                    }
                }

            }
        }

    }

}