pipeline{
    agent any
    tools{
        maven 'Maven 3.8.1'
    }
    stages{
        stage('build'){
            steps{
                echo 'this is build step'
                dir('worker'){
                    sh 'mvn compile'
                } 
            }
        }
        stage('test'){
            steps{
                echo 'this is a test step'
                dir('worker'){
                    sh 'mvn clean test'
                }                
            }
        }
        stage('package'){
            steps{
                echo 'this is a packeging.'
                dir('worker'){
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }
    post{
        always{
	    archieveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            echo 'building multibranch pipeline for worker is completed..'
        }
    }
}
